### PR TITLE
Make Tobira work with PostgreSQL schemas other than `public`

### LINKED ISSUE #635: Tobira only works with "public" schema
Tobira has the `public` schema hard coded (eg. https://github.com/elan-ev/tobira/blob/master/backend/src/db/query.rs) and does not work with other schemas.

### PR DESCRIPTION
**Pull request by LukasKalbertodt**
Fixes #635

This implements what I described in [this comment](https://github.com/elan-ev/tobira/issues/635#issuecomment-1377595429). See commits for further information.

### CODE REVIEW

File: backend/src/db/query.rs [hunk 1]
```diff
@@ -16,12 +16,12 @@ pub(super) async fn all_table_names(db: &impl GenericClient) -> Result<Vec<Strin
...
 }
 
-/// Checks if a table with the name `table_name` exists in the public schema.
+/// Checks if a table with the name `table_name` exists in the current schema.
 pub(super) async fn does_table_exist(db: &impl GenericClient, table_name: &str) -> Result<bool> {
     let row = db.query_one(
         "select exists(
             select * from information_schema.tables
-                where table_schema='public' and table_name=$1
+                where table_schema=current_schema() and table_name=$1
```
Comment (JulianKniephoff) [inline backend/src/db/query.rs:24]:
```suggestion
                where table_schema = current_schema() and table_name=$1
```

File: docs/docs/setup/requirements.md [hunk 2]
```diff
@@ -7,14 +7,22 @@ sidebar_position: 1
...
 
 (If you are a developer, check the `util` folder!)
 
+## Further PostgreSQL requirements
 
+These are technicalities that you likely don't need to care about if you have a dedicated and modern PostgreSQL for Tobira.
+
+- For PostgreSQL version 12 and older, you have to manually enable the `pgcrypto` extension!
+- Over the lifetime of a Tobira installation the `current_schema()` must not change.
+- Tobira needs one schema exclusively.
```
Comment (JulianKniephoff) [inline docs/docs/setup/requirements.md:23]: This suggests it doesn't work with multiple schemas. Maybe rather

```suggestion
- Tobira assumes exclusive control over the `current_schema()`.
```

**Review by JulianKniephoff — CHANGES_REQUESTED** [review]

**Review by JulianKniephoff — APPROVED** [review]
