### PR TITLE
Properly handle HTTP HEAD requests and remove `GET /graphql` route

### LINKED ISSUE #114: HEAD requests always return 404
HTTP HEAD requests for existing sites return a 404 error:

```
% curl -I http://127.0.0.1:3080
HTTP/1.1 404 Not Found
content-type: text/html; charset=UTF-8
content-length: 9741
date: Tue, 08 Dec 2020 17:11:13 GMT
```

…while:

```
% curl -is http://127.0.0.1:3080
HTTP/1.1 200 OK
content-type: text/html; charset=UTF-8
content-length: 9741
date: Tue, 08 Dec 2020 17:12:24 GMT

…
```

### PR DESCRIPTION
**Pull request by LukasKalbertodt**
Fixes #114

The body is automatically removed by `hyper` if the method is HEAD. This PR also removes the `GET /graphql` route (see commit message).

### CODE REVIEW

File: backend/server/src/http/mod.rs [hunk 1]
```diff
@@ -170,50 +170,56 @@ async fn handle(req: Request<Body>, ctx: Arc<Context>) -> Result<Response> {
...
+        // allowed.
+        "/graphql" if method == Method::POST => {
+            juniper_hyper::graphql(ctx.api_root.clone(), ctx.api_context.clone(), req).await?
+        }
+
+        // From this point on, we only support GET and HEAD requests. All others
+        // will result in 404.
+        _ if method != Method::GET && method != Method::HEAD => {
+            reply_404(&ctx.assets, &method, path).await
+        }
```
Comment (JulianKniephoff) [inline backend/server/src/http/mod.rs:191]: Shouldn't this return [405](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405)? :thinking:

**Review by JulianKniephoff — APPROVED** [review]
