### PR TITLE
Return an error from `db::cmd::clear` when user failed to confirm

### LINKED ISSUE #135: `db clear` silently fails without stdin
If no `stdin` is provided, like when the tool is called from an ansible script, `tobira db clear` just aborts without any indication that there was an error:

Ansible deployment:
```
TASK [reset database] **********************************************************
changed: [tobira.opencast.org]
```

Run with no `stdin`:
```
# : | ./tobira db clear
[2020-12-11][22:18:11.247][DEBUG][tobira::db]  Connecting to postgresql://tobira-master-bWFzdGVy:*****@127.0.0.1:5432/tobira-master-bWFzdGVy
[2020-12-11][22:18:11.247][INFO ][tobira::db]  Created database pool
[2020-12-11][22:18:11.262][DEBUG][tobira::db]  Successfully tested database connection with test query
[2020-12-11][22:18:11.262][WARN ][tobira::db::cmd]  You are about to delete all existing data, tables, types and everything in the 'public' schema of the database!

Hostname: v220200330084111611
Database host: 127.0.0.1
Database name: tobira-master-bWFzdGVy

The database currently holds these tables:
 - __db_migrations (5 rows)
 - __xtea_keys (2 rows)
 - realms (43 rows)

Are you sure you want to completely remove everything in this database? This completely drops the 'public' schema. Please double-check the server you are running this on! Type 'yes' to proceed to delete the data.
Answer was not 'yes'. Aborting.
# echo $?
0
```

### PR DESCRIPTION
**Pull request by LukasKalbertodt**
This also makes sure the program exits with the correct return code.

Fixes #135 
Closes #136

### CODE REVIEW

File: backend/server/src/db/cmd.rs [hunk 1]
```diff
@@ -27,15 +27,11 @@ pub(crate) async fn run(cmd: &DbCommand, config: &config::Db) -> Result<()> {
...
-            clear(&mut db, config).await?;
-        }
+        DbCommand::Clear => clear(&mut db, config).await?,
         DbCommand::Migrate => super::migrate(&mut db).await?,
         DbCommand::Reset => {
-            let cleared = clear(&mut db, config).await?;
-            if cleared {
-                super::migrate(&mut db).await?;
-            }
+            clear(&mut db, config).await?;
```
Comment (lkiesow) [inline backend/server/src/db/cmd.rs:33]: Just to make sure I interpret this correctly:
- `bail!` will nor exit `clear(…)` immediately with an `Error`
- The question mark here at the end will ensure the error is thrown further so that Tobira is terminated

Comment (LukasKalbertodt) [reply backend/server/src/db/cmd.rs:33]: `bail!` is like `return Err(...)`, so it does immediately "exit" the function `clear`, but not the program as a whole. The question mark passes errors further up, meaning that it will return an `Err` from `run` if `clear` returns an error. It's equivalent to:

```rust
match clear(&mut db, config).await {
    Ok(_) => {},
    Err(e) => return Err(e),
};
```

So if your "nor" is supposed to mean "now", then yes, you are right.

**Review by lkiesow — APPROVED** [review]
